In [106]:
import pandas as pd
import glob
import numpy as np

In [107]:
filenames = glob.glob("*.csv")

In [108]:
dfs = []
column_names = set()
for filename in filenames:
    if not filename.startswith("aqi"):
        df = pd.read_csv(filename, na_values=[" "]).fillna(0)
        df.columns = [column.strip() for column in df.columns]
        df['province'] = filename[:-4]
        for column_name in df.columns:
            column_names.add(column_name)
        dfs.append(df)

In [109]:
for df in dfs:
    for column_name in column_names:
        if column_name not in df.columns:
            df[column_name] = 0

In [110]:
all_data = pd.concat(dfs, axis=0)

In [111]:
all_data

          date   pm25  pm10    o3   no2   so2   co    province  aqi
0     2021/4/1  132.0  59.0  35.0  12.0   0.0  4.0     Gia Lai  0.0
1     2021/4/2   96.0  41.0  40.0   8.0   1.0  2.0     Gia Lai  0.0
2     2021/4/3   59.0  19.0  25.0   4.0   0.0  1.0     Gia Lai  0.0
3     2021/4/4   21.0  31.0  27.0   5.0   9.0  1.0     Gia Lai  0.0
4     2021/4/5   37.0  28.0  29.0   4.0  10.0  1.0     Gia Lai  0.0
..         ...    ...   ...   ...   ...   ...  ...         ...  ...
139   2019/9/4    0.0   2.0  55.0   6.0   8.0  7.0  Quang Ninh  0.0
140  2019/5/27    0.0   0.0   0.0   0.0   0.0  0.0  Quang Ninh  0.0
141   2019/9/1    0.0   0.0  57.0   6.0   7.0  7.0  Quang Ninh  0.0
142   2019/9/2    0.0   0.0  48.0   5.0   7.0  7.0  Quang Ninh  0.0
143   2019/9/3    0.0   0.0  59.0   7.0   8.0  7.0  Quang Ninh  0.0

[11391 rows x 9 columns]

In [112]:
all_data.loc[all_data["aqi"] == 0, "aqi"] = all_data.loc[all_data["aqi"] == 0, ["pm25", "pm10", "o3", "no2", "so2", "co"]].max(axis=1)

In [113]:
all_data

          date   pm25  pm10    o3   no2   so2   co    province    aqi
0     2021/4/1  132.0  59.0  35.0  12.0   0.0  4.0     Gia Lai  132.0
1     2021/4/2   96.0  41.0  40.0   8.0   1.0  2.0     Gia Lai   96.0
2     2021/4/3   59.0  19.0  25.0   4.0   0.0  1.0     Gia Lai   59.0
3     2021/4/4   21.0  31.0  27.0   5.0   9.0  1.0     Gia Lai   31.0
4     2021/4/5   37.0  28.0  29.0   4.0  10.0  1.0     Gia Lai   37.0
..         ...    ...   ...   ...   ...   ...  ...         ...    ...
139   2019/9/4    0.0   2.0  55.0   6.0   8.0  7.0  Quang Ninh   55.0
140  2019/5/27    0.0   0.0   0.0   0.0   0.0  0.0  Quang Ninh    0.0
141   2019/9/1    0.0   0.0  57.0   6.0   7.0  7.0  Quang Ninh   57.0
142   2019/9/2    0.0   0.0  48.0   5.0   7.0  7.0  Quang Ninh   48.0
143   2019/9/3    0.0   0.0  59.0   7.0   8.0  7.0  Quang Ninh   59.0

[11391 rows x 9 columns]

In [114]:
all_data.to_csv("aqi.csv", index=False)

In [115]:
all_data["province"].unique()

array(['Gia Lai', 'Ha Noi', 'Phu Tho', 'Da Nang', 'Ho Chi Minh',
       'Thua Thien Hue', 'Lao Cai', 'Binh Dinh', 'Thai Nguyen',
       'Khanh Hoa', 'Bac Ninh', 'Quang Ninh'], dtype=object)

In [116]:
all_data[all_data["province"] == "Thai Nguyen"]

           date  pm25   pm10   o3   no2   so2   co     province    aqi
0      2021/4/1  58.0   32.0  0.0  11.0   2.0  5.0  Thai Nguyen   58.0
1      2021/4/2  44.0   36.0  0.0  15.0   2.0  6.0  Thai Nguyen   44.0
2      2021/4/3  43.0   45.0  0.0  13.0  10.0  5.0  Thai Nguyen   45.0
3      2021/4/4  62.0   23.0  0.0   6.0   4.0  5.0  Thai Nguyen   62.0
4      2021/4/5  23.0   48.0  0.0   8.0   6.0  5.0  Thai Nguyen   48.0
..          ...   ...    ...  ...   ...   ...  ...          ...    ...
304  2020/12/26   0.0  116.0  0.0  25.0   2.0  8.0  Thai Nguyen  116.0
305    2020/8/9   0.0   44.0  0.0   0.0   0.0  0.0  Thai Nguyen   44.0
306   2020/6/20   0.0   51.0  0.0   0.0   0.0  0.0  Thai Nguyen   51.0
307  2020/12/12   0.0    0.0  0.0  11.0   0.0  6.0  Thai Nguyen   11.0
308  2020/12/13   0.0    0.0  0.0  10.0   0.0  7.0  Thai Nguyen   10.0

[309 rows x 9 columns]